use_frameworks!

platform :ios, '9.0'

target 'IPaUIKitHelper_Example' do
  pod 'IPaUIKitHelper', :path => '../'

  target 'IPaUIKitHelper_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
